//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace @__LPM.Clientes.MODEL
{
    using System;
    using System.Collections.Generic;
    
    public partial class LPM_Cliente
    {
        public int id { get; set; }
        public string tipo_pessoa { get; set; }
        public string documento { get; set; }
        public string nome { get; set; }
        public string sobrenome { get; set; }
        public string cidade { get; set; }
        public string bairro { get; set; }
        public string logradouro { get; set; }
        public string numero { get; set; }
        public string complemento { get; set; }
        public string ponto_referencia { get; set; }
        public string contato { get; set; }
    }
}
